k=int(input())
print(k,"* 2 =",k*2)
print(k,"* 3 =",k*3)
print(k,"* 4 =",k*4)
print(k,"* 5 =",k*5)
print(k,"* 6 =",k*6)
print(k,"* 7 =",k*7)
print(k,"* 8 =",k*8)
print(k,"* 9 =",k*9)
print(k,"* 10 =",k*10)

